name: Deploy to Configured Media

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Remove Old Configured Media Folder Contents
      run: |
        rm -rf configured.media/*

    - name: Copy Content Folder to Configured Media Folder
      run: |
        mkdir -p configured.media
        cp -r content configured.media/

    - name: Copy Index.html to Configured Media Folder
      run: |
        cp index.html configured.media/

    - name: Commit Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add configured.media/
        git commit -m "Deploy content to configured.media folder"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
